# Generated by Django 4.2.1 on 2023-06-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('nome_disciplina', models.CharField(default='NULL', max_length=20)),
                ('periodo_disciplina', models.IntegerField(default=0)),
            ],
        ),
    ]
