# Generated by Django 4.2.1 on 2023-06-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='tipo_disciplina',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome_disciplina',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='periodo_disciplina',
            field=models.IntegerField(),
        ),
    ]
