# Generated by Django 4.2.1 on 2023-06-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplina', '0002_disciplina_tipo_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='id_disciplina',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
