# Generated by Django 4.2.1 on 2023-06-28 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grade', '0002_alter_grade_id_grade'),
        ('Disciplina', '0004_disciplina_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='curso',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Grade.grade'),
            preserve_default=False,
        ),
    ]
