# Generated by Django 4.2.2 on 2023-06-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('nome_administrador', models.CharField(max_length=60)),
                ('email_administrador', models.EmailField(max_length=254)),
                ('siape_administrador', models.CharField(max_length=7)),
                ('cargo_administrador', models.CharField(max_length=15)),
                ('comorbidade_administrador', models.BooleanField()),
                ('estado_administrador', models.BooleanField()),
            ],
        ),
    ]
