# Generated by Django 4.2.2 on 2023-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='senha_administrador',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
