# Generated by Django 4.2.1 on 2023-06-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_administrador_senha_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='telefone_administrador',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
