# Generated by Django 4.2.1 on 2023-06-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0004_alter_administrador_telefone_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='telefone_administrador',
            field=models.CharField(max_length=12),
        ),
    ]
