# Generated by Django 4.2.1 on 2023-06-28 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0002_alter_curso_id_curso'),
        ('Grade', '0002_alter_grade_id_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Curso.curso'),
            preserve_default=False,
        ),
    ]
