# Generated by Django 4.2.1 on 2023-06-27 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Disciplina', '0003_alter_disciplina_id_disciplina'),
        ('EspacoFisico', '0003_alter_espacofisico_id_espaco_fisico'),
        ('Professor', '0003_alter_professor_id_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id_alocacao', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=15)),
                ('horario_alocacao', models.IntegerField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disciplina.disciplina')),
                ('espaco_fisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EspacoFisico.espacofisico')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professor.professor')),
            ],
        ),
    ]
