# Generated by Django 4.2.1 on 2023-06-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
    ]
