# Generated by Django 4.2.1 on 2023-06-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='area_atuacao_professor',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='professor',
            name='comorbidade',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email_professor',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='professor',
            name='estado_professor',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome_professor',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='professor',
            name='senha_professor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='professor',
            name='siape_professor',
            field=models.CharField(max_length=8),
        ),
    ]
