# Generated by Django 4.2.1 on 2023-06-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0002_alter_professor_area_atuacao_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='id_professor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
