# Generated by Django 4.2.1 on 2023-06-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0003_alter_professor_id_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='siape_professor',
            field=models.CharField(max_length=7),
        ),
    ]
