# Generated by Django 4.2.1 on 2023-06-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspacoFisico',
            fields=[
                ('id_espaco_fisico', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_espaco_fisico', models.CharField(max_length=15)),
                ('dimencoes', models.CharField(default='0', max_length=15)),
                ('capacidade', models.IntegerField()),
                ('bloco', models.CharField(max_length=1)),
                ('andar', models.IntegerField()),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
