# Generated by Django 4.2.1 on 2023-06-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspacoFisico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacofisico',
            name='bloco',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='espacofisico',
            name='dimencoes',
            field=models.CharField(max_length=15),
        ),
    ]
